// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXR2EaHZazNIOxU4ETg-0VEECByyz5ItY',
    appId: '1:690122025412:web:395c22f10b374354fb5c91',
    messagingSenderId: '690122025412',
    projectId: 'tasks-4a51b',
    authDomain: 'tasks-4a51b.firebaseapp.com',
    storageBucket: 'tasks-4a51b.firebasestorage.app',
    measurementId: 'G-TGVDY29PBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaa4e78gx0Li6Ipk1SPBWjfFF6VpLaXWg',
    appId: '1:690122025412:android:16c2d29dec44eb54fb5c91',
    messagingSenderId: '690122025412',
    projectId: 'tasks-4a51b',
    storageBucket: 'tasks-4a51b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-DIfXbkiJ6ebkDf6MAwaIOrCIG0aPjOc',
    appId: '1:690122025412:ios:215dc7d26a85bae0fb5c91',
    messagingSenderId: '690122025412',
    projectId: 'tasks-4a51b',
    storageBucket: 'tasks-4a51b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-DIfXbkiJ6ebkDf6MAwaIOrCIG0aPjOc',
    appId: '1:690122025412:ios:215dc7d26a85bae0fb5c91',
    messagingSenderId: '690122025412',
    projectId: 'tasks-4a51b',
    storageBucket: 'tasks-4a51b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXR2EaHZazNIOxU4ETg-0VEECByyz5ItY',
    appId: '1:690122025412:web:5a460134ce0cb986fb5c91',
    messagingSenderId: '690122025412',
    projectId: 'tasks-4a51b',
    authDomain: 'tasks-4a51b.firebaseapp.com',
    storageBucket: 'tasks-4a51b.firebasestorage.app',
    measurementId: 'G-N7GK4TRZ3N',
  );
}
